name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

env:
  IMAGE_NAME: ghcr.io/moolen/skouter

jobs:
  docker:
    outputs:
      image-tag: ${{ steps.version.outputs.version }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate tmp version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION=$(echo "v0.0.0-$(git rev-list HEAD --count)-g$(git describe --dirty --always)" | sed 's/-/./2' | sed 's/-/./2')
          fi
          echo "::set-output name=version::${VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        id: build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  sign:
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "sign image"
      uses: ./.github/actions/sign
      with:
        image-name: ${{ env.IMAGE_NAME }}
        image-tag: ${{ needs.docker.outputs.image-tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
